name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to VPS via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 89.42.199.153
          port: 43785
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "."
          target: "/root/fastapi-request-logger"
          overwrite: true
          strip_components: 1

      - name: Run deployment script on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 89.42.199.153
          port: 43785
          username: root
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /root/fastapi-request-logger
            chmod +x run.sh
            ./run.sh
