name: Deploy FastAPI Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no hashemi@192.168.11.70 << 'EOF'
            set -e

            cd /home/hashemi/Desktop/fastapi-request-logger

            echo "Pulling latest code..."
            git pull origin main

            echo "Stopping old container (if exists)..."
            docker ps -q --filter "name=request_logger" | grep -q . && docker stop request_logger && docker rm request_logger || echo "No container to stop."

            echo "Building Docker image..."
            docker build -t request-logger .

            echo "Running Docker container..."
            docker run -d --name request_logger -p 9002:9002 request-logger
          EOF
