name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@89.42.199.153 << 'EOF'
            set -e

            # اگر پروژه وجود نداره، کلونش کن
            if [ ! -d /root/fastapi-request-logger ]; then
              git clone git@github.com:MrMrProgrammer/fastapi-request-logger.git /root/fastapi-request-logger
            fi

            cd /root/fastapi-request-logger
            git pull origin main

            # حذف کانتینرهای قبلی (اگر هستن)
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker stop grafana || true
            docker rm grafana || true
            docker stop tempo || true
            docker rm tempo || true

            # اجرای مجدد run.sh
            chmod +x run.sh
            ./run.sh
          EOF
